services:
  db:
    image: postgres:16
    container_name: kolvix-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sysdevjdz26
      POSTGRES_DB: kolvix_bd
    ports:
      - '5432:5432'
    volumes:
      - kolvix-db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  kolvix-db-data:
