-- ============================================================
--  KOLVIX - DDL
-- ============================================================

-- ============================================================
--  1. PLANES DE SUSCRIPCION
-- ============================================================

CREATE TABLE planes_suscripcion (
    codigo          VARCHAR(20)     PRIMARY KEY,
    nombre          VARCHAR(80)     NOT NULL,
    descripcion     VARCHAR(255),
    monto_mensual   NUMERIC(10,2)   NOT NULL CHECK (monto_mensual >= 0),
    moneda          VARCHAR(3)         NOT NULL DEFAULT 'HNL',
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);

INSERT INTO planes_suscripcion
    (codigo, nombre, descripcion, monto_mensual, moneda)
VALUES
    ('BASICO', 'Basico', 'Plan inicial para talleres pequenos.', 250.00, 'HNL'),
    ('PROFESIONAL', 'Profesional', 'Plan para talleres con inventario y notificaciones.', 500.00, 'HNL'),
    ('EMPRESARIAL', 'Empresarial', 'Plan para talleres con mayor volumen operativo.', 1500.00, 'HNL');


-- ============================================================
--  2. CUENTAS DE COBRO
-- ============================================================

CREATE TABLE cuentas_cobro (
    id_cuenta       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    banco           VARCHAR(100)    NOT NULL,
    tipo_cuenta     VARCHAR(20)     NOT NULL DEFAULT 'AHORRO'
        CHECK (tipo_cuenta IN ('AHORRO', 'CHEQUES', 'OTRO')),
    numero_cuenta   VARCHAR(50)     NOT NULL,
    titular         VARCHAR(120)    NOT NULL,
    moneda          VARCHAR(3)         NOT NULL DEFAULT 'HNL',
    instrucciones   VARCHAR(255),
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  3. EMPRESA
-- ============================================================

CREATE TABLE empresas (
    id_empresa          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre              VARCHAR(100)    NOT NULL,
    rtn                 VARCHAR(20)     UNIQUE,
    telefono            VARCHAR(20),
    correo              VARCHAR(100)    NOT NULL UNIQUE,
    direccion           VARCHAR(255),
    fecha_registro      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    plan_suscripcion    VARCHAR(20)     NOT NULL DEFAULT 'BASICO'
        REFERENCES planes_suscripcion(codigo) ON DELETE RESTRICT,
    activo              BOOLEAN         NOT NULL DEFAULT TRUE,
    updated_at          TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  4. CUENTAS DE PAGO DEL TALLER
-- ============================================================

CREATE TABLE cuentas_pago_taller (
    id_cuenta       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa      BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    banco           VARCHAR(100)    NOT NULL,
    tipo_cuenta     VARCHAR(20)     NOT NULL DEFAULT 'AHORRO'
        CHECK (tipo_cuenta IN ('AHORRO', 'CHEQUES', 'OTRO')),
    numero_cuenta   VARCHAR(50)     NOT NULL,
    titular         VARCHAR(120)    NOT NULL,
    moneda          VARCHAR(3)         NOT NULL DEFAULT 'HNL',
    instrucciones   VARCHAR(255),
    activo          BOOLEAN         NOT NULL DEFAULT TRUE,
    updated_at      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_cuenta_pago_taller UNIQUE (id_empresa, banco, numero_cuenta),
    CONSTRAINT uq_cuenta_pago_taller_empresa_id UNIQUE (id_empresa, id_cuenta)
);


-- ============================================================
--  5. USUARIOS
-- ============================================================

CREATE TABLE usuarios (
    id_usuario              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa              BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre                  VARCHAR(50)     NOT NULL,
    apellido                VARCHAR(50)     NOT NULL,
    correo                  VARCHAR(100)    NOT NULL,
    password_hash           VARCHAR(255)    NOT NULL,
    rol                     VARCHAR(20)     NOT NULL DEFAULT 'RECEPCIONISTA'
        CHECK (rol IN ('ADMIN', 'TECNICO', 'RECEPCIONISTA', 'PROPIETARIO')),
    activo                  BOOLEAN         NOT NULL DEFAULT TRUE,
    debe_cambiar_password   BOOLEAN         NOT NULL DEFAULT FALSE,
    ultimo_acceso           TIMESTAMPTZ,
    updated_at              TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_usuario_correo_empresa UNIQUE (id_empresa, correo),
    CONSTRAINT uq_usuario_empresa_id UNIQUE (id_empresa, id_usuario)
);


-- ============================================================
--  6. TECNICOS
-- ============================================================

CREATE TABLE tecnicos (
    id_tecnico                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa                    BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_usuario                    BIGINT          NOT NULL UNIQUE,
    dni                           VARCHAR(20)     NOT NULL,
    rtn                           VARCHAR(20),
    direccion                     VARCHAR(255),
    telefono                      VARCHAR(20)     NOT NULL,
    fecha_nacimiento              DATE,
    nombre_contacto_emergencia    VARCHAR(100),
    telefono_contacto_emergencia  VARCHAR(20),
    url_fotografia                VARCHAR(255),
    activo                        BOOLEAN         NOT NULL DEFAULT TRUE,

    CONSTRAINT fk_tecnico_usuario_empresa
        FOREIGN KEY (id_empresa, id_usuario)
        REFERENCES usuarios(id_empresa, id_usuario)
        ON DELETE RESTRICT,
    CONSTRAINT uq_tecnico_dni_empresa UNIQUE (id_empresa, dni),
    CONSTRAINT uq_tecnico_usuario_empresa UNIQUE (id_empresa, id_usuario),
    CONSTRAINT uq_tecnico_empresa_id UNIQUE (id_empresa, id_tecnico)
);


-- ============================================================
--  7. CLIENTES
-- ============================================================

CREATE TABLE clientes (
    id_cliente          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa          BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre              VARCHAR(50)     NOT NULL,
    apellido            VARCHAR(50)     NOT NULL,
    dni                 VARCHAR(20),
    telefono            VARCHAR(20),
    correo              VARCHAR(100),
    direccion           VARCHAR(255),
    fecha_registro      TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_cliente_dni_empresa UNIQUE (id_empresa, dni),
    CONSTRAINT uq_cliente_empresa_id UNIQUE (id_empresa, id_cliente)
);


-- ============================================================
--  8. CATEGORIAS DE DISPOSITIVOS - catalogo global
-- ============================================================

CREATE TABLE categoria_dispositivos (
    id_categoria        SERIAL          PRIMARY KEY,
    nombre              VARCHAR(80)     NOT NULL UNIQUE,
    descripcion         VARCHAR(255)
);

INSERT INTO categoria_dispositivos (nombre) VALUES
    ('Celular / Smartphone'),
    ('Computadora portatil'),
    ('Computadora de escritorio'),
    ('Tablet'),
    ('Consola de videojuegos'),
    ('Televisor'),
    ('Electrodomestico'),
    ('Impresora'),
    ('Otro');


-- ============================================================
--  9. DISPOSITIVOS
-- ============================================================

CREATE TABLE dispositivos (
    id_dispositivo              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa                  BIGINT          NOT NULL,
    id_cliente                  BIGINT          NOT NULL,
    id_categoria_dispositivo    INT             NOT NULL REFERENCES categoria_dispositivos(id_categoria),
    marca                       VARCHAR(50),
    modelo                      VARCHAR(50),
    numero_serie                VARCHAR(80),
    color                       VARCHAR(30),
    descripcion_equipo          VARCHAR(255),
    accesorios_recibidos        TEXT,

    CONSTRAINT fk_dispositivo_cliente_empresa
        FOREIGN KEY (id_empresa, id_cliente)
        REFERENCES clientes(id_empresa, id_cliente)
        ON DELETE RESTRICT,
    CONSTRAINT uq_dispositivo_empresa_id UNIQUE (id_empresa, id_dispositivo),
    CONSTRAINT uq_dispositivo_cliente_id UNIQUE (id_cliente, id_dispositivo)
);


-- ============================================================
--  10. ESTADOS DE REPARACION - personalizable por empresa
-- ============================================================

CREATE TABLE estados_reparacion (
    id_estado           SERIAL          PRIMARY KEY,
    id_empresa          BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    nombre              VARCHAR(50)     NOT NULL,
    color_hex           VARCHAR(7)      NOT NULL DEFAULT '#6B7280',
    orden               SMALLINT        NOT NULL DEFAULT 0,
    es_estado_final     BOOLEAN         NOT NULL DEFAULT FALSE,
    notificar_cliente   BOOLEAN         NOT NULL DEFAULT FALSE,

    CONSTRAINT uq_estado_nombre_empresa UNIQUE (id_empresa, nombre),
    CONSTRAINT uq_estado_empresa_id UNIQUE (id_empresa, id_estado)
);


-- ============================================================
--  11. ORDENES DE TRABAJO - nucleo del sistema
-- ============================================================

CREATE TABLE ordenes_trabajo (
    id_orden             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa           BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    id_cliente           BIGINT          NOT NULL,
    id_dispositivo       BIGINT          NOT NULL,
    id_tecnico           BIGINT,
    id_estado            INT             NOT NULL,
    numero_orden         VARCHAR(20)     NOT NULL,
    codigo_seguimiento   VARCHAR(20)     NOT NULL,
    problema_reportado   VARCHAR(500)    NOT NULL,
    fecha_ingreso        TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    fecha_entrega        TIMESTAMPTZ,
    fecha_cierre         TIMESTAMPTZ,
    observaciones        VARCHAR(300),
    estado_pago          VARCHAR(20)     NOT NULL DEFAULT 'NO_SOLICITADO'
        CHECK (estado_pago IN ('NO_SOLICITADO', 'PENDIENTE', 'EN_REVISION', 'PAGADO', 'RECHAZADO')),
    updated_at           TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT fk_orden_cliente_empresa
        FOREIGN KEY (id_empresa, id_cliente)
        REFERENCES clientes(id_empresa, id_cliente)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orden_dispositivo_empresa
        FOREIGN KEY (id_empresa, id_dispositivo)
        REFERENCES dispositivos(id_empresa, id_dispositivo)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orden_dispositivo_cliente
        FOREIGN KEY (id_cliente, id_dispositivo)
        REFERENCES dispositivos(id_cliente, id_dispositivo)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orden_tecnico_empresa
        FOREIGN KEY (id_empresa, id_tecnico)
        REFERENCES tecnicos(id_empresa, id_tecnico)
        ON DELETE RESTRICT,
    CONSTRAINT fk_orden_estado_empresa
        FOREIGN KEY (id_empresa, id_estado)
        REFERENCES estados_reparacion(id_empresa, id_estado)
        ON DELETE RESTRICT,
    CONSTRAINT uq_orden_numero_empresa UNIQUE (id_empresa, numero_orden),
    CONSTRAINT uq_orden_codigo_seguimiento UNIQUE (codigo_seguimiento),
    CONSTRAINT uq_orden_empresa_id UNIQUE (id_empresa, id_orden)
);


-- ============================================================
--  12. HISTORIAL DE ORDENES
-- ============================================================

CREATE TABLE historial_ordenes (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden            BIGINT          NOT NULL REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_usuario          BIGINT          NOT NULL REFERENCES usuarios(id_usuario),
    id_estado_nuevo     INT             NOT NULL REFERENCES estados_reparacion(id_estado),
    id_estado_anterior  INT             REFERENCES estados_reparacion(id_estado),
    comentario          TEXT,
    fecha               TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  13. DIAGNOSTICOS
-- ============================================================

CREATE TABLE diagnosticos (
    id_diagnostico             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa                 BIGINT          NOT NULL,
    id_orden                   BIGINT          NOT NULL,
    id_tecnico                 BIGINT          NOT NULL,
    problema_encontrado        TEXT            NOT NULL,
    causa_raiz                 TEXT,
    tiempo_estimado_horas      NUMERIC(5,2),
    complejidad                VARCHAR(20)
        CHECK (complejidad IS NULL OR complejidad IN ('BAJA', 'MEDIA', 'ALTA')),
    fecha_diagnostico          TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    observaciones_adicionales  TEXT,

    CONSTRAINT fk_diagnostico_orden_empresa
        FOREIGN KEY (id_empresa, id_orden)
        REFERENCES ordenes_trabajo(id_empresa, id_orden)
        ON DELETE CASCADE,
    CONSTRAINT fk_diagnostico_tecnico_empresa
        FOREIGN KEY (id_empresa, id_tecnico)
        REFERENCES tecnicos(id_empresa, id_tecnico)
        ON DELETE RESTRICT,
    CONSTRAINT uq_diagnostico_empresa_id UNIQUE (id_empresa, id_diagnostico),
    CONSTRAINT ck_diagnostico_tiempo_no_negativo CHECK (
        tiempo_estimado_horas IS NULL OR tiempo_estimado_horas >= 0
    )
);


-- ============================================================
--  14. COTIZACIONES - fase clave del MVP
-- ============================================================

CREATE TABLE cotizaciones (
    id_cotizacion              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa                 BIGINT          NOT NULL,
    id_orden                   BIGINT          NOT NULL,
    id_diagnostico             BIGINT          NOT NULL,
    id_usuario_creador         BIGINT          NOT NULL,
    version                    SMALLINT        NOT NULL DEFAULT 1,
    monto_mano_obra            NUMERIC(10,2)   NOT NULL DEFAULT 0,
    monto_repuestos            NUMERIC(10,2)   NOT NULL DEFAULT 0,
    monto_total                NUMERIC(10,2)   NOT NULL DEFAULT 0,
    tiempo_estimado_horas      NUMERIC(5,2),
    estado                     VARCHAR(20)     NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'ENVIADA', 'APROBADA', 'RECHAZADA', 'VENCIDA', 'CANCELADA')),
    fecha_creacion             TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    fecha_envio                TIMESTAMPTZ,
    fecha_respuesta            TIMESTAMPTZ,
    observacion_cliente        VARCHAR(500),
    observacion_interna        VARCHAR(500),

    CONSTRAINT fk_cotizacion_orden_empresa
        FOREIGN KEY (id_empresa, id_orden)
        REFERENCES ordenes_trabajo(id_empresa, id_orden)
        ON DELETE CASCADE,
    CONSTRAINT fk_cotizacion_diagnostico
        FOREIGN KEY (id_empresa, id_diagnostico)
        REFERENCES diagnosticos(id_empresa, id_diagnostico)
        ON DELETE RESTRICT,
    CONSTRAINT fk_cotizacion_usuario_empresa
        FOREIGN KEY (id_empresa, id_usuario_creador)
        REFERENCES usuarios(id_empresa, id_usuario)
        ON DELETE RESTRICT,
    CONSTRAINT uq_cotizacion_version_diagnostico UNIQUE (id_diagnostico, version),
    CONSTRAINT uq_cotizacion_empresa_id UNIQUE (id_empresa, id_cotizacion),
    CONSTRAINT ck_cotizacion_montos_no_negativos CHECK (
        monto_mano_obra >= 0
        AND monto_repuestos >= 0
        AND monto_total >= 0
        AND (tiempo_estimado_horas IS NULL OR tiempo_estimado_horas >= 0)
    )
);


-- ============================================================
--  15. PLANTILLAS DE INSPECCION
-- ============================================================

CREATE TABLE plantillas_inspeccion (
    id_plantilla   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_categoria   INT             NOT NULL REFERENCES categoria_dispositivos(id_categoria),
    nombre         VARCHAR(100)    NOT NULL,
    descripcion    VARCHAR(255),
    vistas         JSONB           NOT NULL DEFAULT '[]'::jsonb,
    activo         BOOLEAN         NOT NULL DEFAULT TRUE,
    fecha_creacion TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_plantilla_categoria_nombre UNIQUE (id_categoria, nombre)
);


-- ============================================================
--  16. CHECKLISTS DE RECEPCION
-- ============================================================

CREATE TABLE checklists_recepcion (
    id_checklist             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden                 BIGINT          NOT NULL REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_usuario               BIGINT          NOT NULL REFERENCES usuarios(id_usuario),
    id_plantilla_inspeccion  BIGINT          REFERENCES plantillas_inspeccion(id_plantilla),
    estado_fisico_general    VARCHAR(30)
        CHECK (estado_fisico_general IS NULL OR estado_fisico_general IN ('BUENO', 'REGULAR', 'DANIADO', 'NO_APLICA')),
    danos_fisicos            JSONB           NOT NULL DEFAULT '[]'::jsonb,
    observaciones            VARCHAR(500),
    aceptacion_cliente       BOOLEAN         NOT NULL DEFAULT FALSE,
    url_documento_aceptacion VARCHAR(255),
    fecha_aceptacion         TIMESTAMPTZ,
    fecha                    TIMESTAMPTZ     NOT NULL DEFAULT NOW(),

    CONSTRAINT uq_checklist_orden UNIQUE (id_orden)
);


-- ============================================================
--  17. CONTROLES DE CALIDAD
-- ============================================================

CREATE TABLE controles_calidad (
    id_control           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden             BIGINT          NOT NULL REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_usuario           BIGINT          NOT NULL REFERENCES usuarios(id_usuario),
    pruebas_realizadas   JSONB           NOT NULL DEFAULT '[]'::jsonb,
    resultado_general    VARCHAR(20)     NOT NULL DEFAULT 'PENDIENTE'
        CHECK (resultado_general IN ('PENDIENTE', 'APROBADO', 'RECHAZADO')),
    observaciones        TEXT,
    fecha_control        TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  18. ENTREGAS
-- ============================================================

CREATE TABLE entregas (
    id_entrega              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden                BIGINT          NOT NULL UNIQUE REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_usuario_entrega      BIGINT          NOT NULL REFERENCES usuarios(id_usuario),
    identidad_verificada    BOOLEAN         NOT NULL DEFAULT FALSE,
    url_comprobante_entrega VARCHAR(255),
    observaciones           TEXT,
    fecha_entrega           TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  19. PAGOS DE ORDENES
-- ============================================================

CREATE TABLE pagos_orden (
    id_pago              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa           BIGINT          NOT NULL,
    id_orden             BIGINT          NOT NULL,
    id_cuenta            BIGINT,
    monto                NUMERIC(10,2)   NOT NULL CHECK (monto > 0),
    moneda               VARCHAR(3)         NOT NULL DEFAULT 'HNL',
    metodo               VARCHAR(20)     NOT NULL DEFAULT 'DEPOSITO'
        CHECK (metodo IN ('DEPOSITO', 'TRANSFERENCIA')),
    estado               VARCHAR(20)     NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'VERIFICADO', 'RECHAZADO')),
    referencia           VARCHAR(100),
    url_comprobante      VARCHAR(255)    NOT NULL,
    observacion_cliente  VARCHAR(255),
    observacion_taller   VARCHAR(255),
    fecha_subida         TIMESTAMPTZ     NOT NULL DEFAULT NOW(),
    fecha_verificacion   TIMESTAMPTZ,
    id_usuario_verifica  BIGINT,

    CONSTRAINT fk_pago_orden_empresa
        FOREIGN KEY (id_empresa, id_orden)
        REFERENCES ordenes_trabajo(id_empresa, id_orden)
        ON DELETE CASCADE,
    CONSTRAINT fk_pago_cuenta_empresa
        FOREIGN KEY (id_empresa, id_cuenta)
        REFERENCES cuentas_pago_taller(id_empresa, id_cuenta)
        ON DELETE RESTRICT,
    CONSTRAINT fk_pago_usuario_verifica_empresa
        FOREIGN KEY (id_empresa, id_usuario_verifica)
        REFERENCES usuarios(id_empresa, id_usuario)
        ON DELETE RESTRICT
);


-- ============================================================
--  20. ALBUMES DE EVIDENCIA
-- ============================================================

CREATE TABLE albumes_evidencia (
    id_album        SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo          VARCHAR(30)     NOT NULL UNIQUE
        CHECK (codigo IN ('RECEPCION', 'DIAGNOSTICO', 'REPARACION', 'CONTROL_CALIDAD', 'ENTREGA')),
    titulo          VARCHAR(100)    NOT NULL,
    descripcion     VARCHAR(255),
    obligatorio     BOOLEAN         NOT NULL DEFAULT FALSE,
    orden           SMALLINT        NOT NULL DEFAULT 0,
    activo          BOOLEAN         NOT NULL DEFAULT TRUE
);

INSERT INTO albumes_evidencia
    (codigo, titulo, descripcion, obligatorio, orden)
VALUES
    ('RECEPCION', 'Recepcion del equipo', 'Evidencia del estado fisico al recibir el equipo.', TRUE, 1),
    ('DIAGNOSTICO', 'Diagnostico tecnico', 'Evidencia de hallazgos tecnicos y danos internos.', FALSE, 2),
    ('REPARACION', 'Proceso de reparacion', 'Evidencia del avance, repuestos y pruebas durante la reparacion.', FALSE, 3),
    ('CONTROL_CALIDAD', 'Control de calidad', 'Evidencia de pruebas finales antes de entrega.', FALSE, 4),
    ('ENTREGA', 'Entrega del equipo', 'Evidencia del estado final del equipo al entregarlo.', TRUE, 5);


-- ============================================================
--  21. EVIDENCIAS FOTOGRAFICAS
-- ============================================================

CREATE TABLE evidencias_fotograficas (
    id_evidencia      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden          BIGINT          NOT NULL REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_album          SMALLINT        NOT NULL REFERENCES albumes_evidencia(id_album) ON DELETE RESTRICT,
    id_usuario_subida BIGINT          REFERENCES usuarios(id_usuario),
    etiqueta          VARCHAR(50),
    url_imagen        VARCHAR(255)    NOT NULL,
    descripcion       VARCHAR(255),
    obligatorio       BOOLEAN         NOT NULL DEFAULT FALSE,
    orden             SMALLINT        NOT NULL DEFAULT 0,
    fecha_subida      TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  22. REPUESTOS
-- ============================================================

CREATE TABLE repuestos (
    id_repuesto       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa        BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE RESTRICT,
    nombre            VARCHAR(100)    NOT NULL,
    codigo            VARCHAR(80),
    marca             VARCHAR(80),
    stock_actual      INT             NOT NULL DEFAULT 0 CHECK (stock_actual >= 0),
    stock_minimo      INT             NOT NULL DEFAULT 0 CHECK (stock_minimo >= 0),
    precio_costo      NUMERIC(10,2)   NOT NULL DEFAULT 0 CHECK (precio_costo >= 0),
    precio_venta      NUMERIC(10,2)   NOT NULL DEFAULT 0 CHECK (precio_venta >= 0),
    activo            BOOLEAN         NOT NULL DEFAULT TRUE,

    CONSTRAINT uq_repuesto_codigo_empresa UNIQUE (id_empresa, codigo),
    CONSTRAINT uq_repuesto_empresa_id UNIQUE (id_empresa, id_repuesto)
);


-- ============================================================
--  23. REPUESTOS REQUERIDOS EN DIAGNOSTICO
-- ============================================================

CREATE TABLE diagnosticos_repuestos (
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa          BIGINT          NOT NULL,
    id_diagnostico      BIGINT          NOT NULL,
    id_repuesto         BIGINT,
    nombre_repuesto     VARCHAR(100)    NOT NULL,
    cantidad            INT             NOT NULL CHECK (cantidad > 0),
    precio_unitario     NUMERIC(10,2)   NOT NULL CHECK (precio_unitario >= 0),
    subtotal            NUMERIC(10,2)   GENERATED ALWAYS AS (cantidad * precio_unitario) STORED,
    observacion         VARCHAR(255),

    CONSTRAINT fk_diagnostico_repuesto_diagnostico
        FOREIGN KEY (id_empresa, id_diagnostico)
        REFERENCES diagnosticos(id_empresa, id_diagnostico)
        ON DELETE CASCADE,
    CONSTRAINT fk_diagnostico_repuesto_repuesto
        FOREIGN KEY (id_empresa, id_repuesto)
        REFERENCES repuestos(id_empresa, id_repuesto)
        ON DELETE RESTRICT,
    CONSTRAINT ck_diagnostico_repuesto_referencia CHECK (
        id_repuesto IS NOT NULL OR LENGTH(TRIM(nombre_repuesto)) > 0
    )
);


-- ============================================================
--  24. MOVIMIENTOS DE INVENTARIO
-- ============================================================

CREATE TABLE movimientos_inventario (
    id_movimiento      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_repuesto        BIGINT          NOT NULL REFERENCES repuestos(id_repuesto) ON DELETE RESTRICT,
    id_orden           BIGINT          REFERENCES ordenes_trabajo(id_orden) ON DELETE SET NULL,
    id_usuario         BIGINT          REFERENCES usuarios(id_usuario),
    tipo_movimiento    VARCHAR(20)     NOT NULL
        CHECK (tipo_movimiento IN ('ENTRADA', 'SALIDA', 'AJUSTE', 'DEVOLUCION')),
    cantidad           INT             NOT NULL CHECK (cantidad > 0),
    precio_unitario    NUMERIC(10,2)   NOT NULL DEFAULT 0 CHECK (precio_unitario >= 0),
    observacion        VARCHAR(255),
    fecha_movimiento   TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  25. REPUESTOS USADOS EN ORDENES
-- ============================================================

CREATE TABLE repuestos_ordenes (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden         BIGINT          NOT NULL REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_repuesto      BIGINT          NOT NULL REFERENCES repuestos(id_repuesto) ON DELETE RESTRICT,
    cantidad         INT             NOT NULL CHECK (cantidad > 0),
    precio_unitario  NUMERIC(10,2)   NOT NULL CHECK (precio_unitario >= 0),

    CONSTRAINT uq_repuesto_por_orden UNIQUE (id_orden, id_repuesto)
);


-- ============================================================
--  26. NOTIFICACIONES
-- ============================================================

CREATE TABLE notificaciones (
    id_notificacion    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa         BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    id_orden           BIGINT          REFERENCES ordenes_trabajo(id_orden) ON DELETE SET NULL,
    id_cliente         BIGINT          REFERENCES clientes(id_cliente) ON DELETE SET NULL,
    canal              VARCHAR(20)     NOT NULL
        CHECK (canal IN ('WHATSAPP', 'EMAIL')),
    destinatario       VARCHAR(200)    NOT NULL,
    asunto             VARCHAR(255),
    cuerpo             TEXT            NOT NULL,
    estado             VARCHAR(20)     NOT NULL DEFAULT 'PENDIENTE'
        CHECK (estado IN ('PENDIENTE', 'ENVIADO', 'FALLIDO', 'CANCELADO')),
    fecha_programada   TIMESTAMPTZ,
    fecha_envio        TIMESTAMPTZ,
    intentos           SMALLINT        NOT NULL DEFAULT 0 CHECK (intentos >= 0),
    error_envio        TEXT
);


-- ============================================================
--  27. PERFIL MARKETPLACE
-- ============================================================

CREATE TABLE perfiles_marketplace (
    id_marketplace        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_empresa            BIGINT          NOT NULL UNIQUE REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    descripcion_publica   TEXT,
    horario_atencion      VARCHAR(255),
    latitud               NUMERIC(10,7),
    longitud              NUMERIC(10,7),
    marketplace_visible   BOOLEAN         NOT NULL DEFAULT FALSE,
    calificacion_promedio NUMERIC(3,2)    NOT NULL DEFAULT 0.00,
    total_reviews         INT             NOT NULL DEFAULT 0,
    fecha_actualizacion   TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  28. CATEGORIAS DE SERVICIO / CATEGORIAS ATENDIDAS
-- ============================================================

CREATE TABLE categorias_servicio (
    id            SERIAL      PRIMARY KEY,
    id_empresa    BIGINT      NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    id_categoria  INT         NOT NULL REFERENCES categoria_dispositivos(id_categoria),

    CONSTRAINT uq_categoria_servicio UNIQUE (id_empresa, id_categoria)
);


-- ============================================================
--  29. REVIEWS
-- ============================================================

CREATE TABLE reviews (
    id_review      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_orden       BIGINT          NOT NULL UNIQUE REFERENCES ordenes_trabajo(id_orden) ON DELETE CASCADE,
    id_empresa     BIGINT          NOT NULL REFERENCES empresas(id_empresa) ON DELETE CASCADE,
    id_cliente     BIGINT          NOT NULL REFERENCES clientes(id_cliente) ON DELETE CASCADE,
    calificacion   SMALLINT        NOT NULL CHECK (calificacion BETWEEN 1 AND 5),
    comentario     VARCHAR(500),
    fecha_review   TIMESTAMPTZ     NOT NULL DEFAULT NOW()
);


-- ============================================================
--  INDICES
-- ============================================================

-- Suscripcion y cobro
CREATE INDEX idx_plan_activo              ON planes_suscripcion(activo);
CREATE INDEX idx_cuenta_cobro_activa      ON cuentas_cobro(activo, moneda);
CREATE INDEX idx_cuenta_pago_taller       ON cuentas_pago_taller(id_empresa, activo);

-- Ordenes de trabajo
CREATE INDEX idx_orden_empresa_fecha      ON ordenes_trabajo(id_empresa, fecha_ingreso DESC);
CREATE INDEX idx_orden_estado             ON ordenes_trabajo(id_estado);
CREATE INDEX idx_orden_tecnico            ON ordenes_trabajo(id_tecnico) WHERE id_tecnico IS NOT NULL;
CREATE INDEX idx_orden_cliente            ON ordenes_trabajo(id_cliente);
CREATE INDEX idx_orden_codigo_seguimiento ON ordenes_trabajo(codigo_seguimiento);
CREATE INDEX idx_orden_estado_pago        ON ordenes_trabajo(id_empresa, estado_pago);

-- Historial
CREATE INDEX idx_historial_orden          ON historial_ordenes(id_orden, fecha DESC);

-- Diagnosticos y cotizaciones
CREATE INDEX idx_diagnostico_orden        ON diagnosticos(id_empresa, id_orden, fecha_diagnostico DESC);
CREATE INDEX idx_diagnostico_tecnico      ON diagnosticos(id_empresa, id_tecnico);
CREATE INDEX idx_diagnostico_repuesto_diag ON diagnosticos_repuestos(id_empresa, id_diagnostico);
CREATE INDEX idx_diagnostico_repuesto_rep ON diagnosticos_repuestos(id_empresa, id_repuesto) WHERE id_repuesto IS NOT NULL;
CREATE INDEX idx_cotizacion_orden         ON cotizaciones(id_empresa, id_orden, version DESC);
CREATE INDEX idx_cotizacion_diagnostico   ON cotizaciones(id_diagnostico);
CREATE INDEX idx_cotizacion_estado        ON cotizaciones(estado);

-- Checklist y control de calidad
CREATE INDEX idx_plantilla_categoria      ON plantillas_inspeccion(id_categoria, activo);
CREATE INDEX idx_control_calidad_orden    ON controles_calidad(id_orden);

-- Pagos
CREATE INDEX idx_pago_orden               ON pagos_orden(id_empresa, id_orden, fecha_subida DESC);
CREATE INDEX idx_pago_estado              ON pagos_orden(id_empresa, estado, fecha_subida DESC);
CREATE INDEX idx_pago_cuenta              ON pagos_orden(id_empresa, id_cuenta) WHERE id_cuenta IS NOT NULL;
CREATE UNIQUE INDEX uq_pago_verificado_orden ON pagos_orden(id_empresa, id_orden) WHERE estado = 'VERIFICADO';

-- Albumes y evidencia
CREATE INDEX idx_album_codigo             ON albumes_evidencia(codigo, activo);
CREATE INDEX idx_evidencia_album          ON evidencias_fotograficas(id_album, orden, fecha_subida);
CREATE INDEX idx_evidencia_orden          ON evidencias_fotograficas(id_orden, fecha_subida DESC);

-- Inventario
CREATE INDEX idx_movimiento_repuesto      ON movimientos_inventario(id_repuesto, fecha_movimiento DESC);
CREATE INDEX idx_movimiento_orden         ON movimientos_inventario(id_orden) WHERE id_orden IS NOT NULL;
CREATE INDEX idx_repuesto_stock_bajo      ON repuestos(id_empresa) WHERE stock_actual <= stock_minimo AND activo = TRUE;
CREATE INDEX idx_repuesto_empresa         ON repuestos(id_empresa, activo);

-- Notificaciones
CREATE INDEX idx_notif_pendiente          ON notificaciones(estado, fecha_programada) WHERE estado = 'PENDIENTE';
CREATE INDEX idx_notif_orden              ON notificaciones(id_orden) WHERE id_orden IS NOT NULL;

-- Marketplace
CREATE INDEX idx_marketplace_visible      ON perfiles_marketplace(marketplace_visible, calificacion_promedio DESC) WHERE marketplace_visible = TRUE;
-- Indice geoespacial con PostGIS para una fase posterior:
-- CREATE INDEX idx_marketplace_geo ON perfiles_marketplace USING GIST (ubicacion);

-- Tecnicos y usuarios
CREATE INDEX idx_tecnico_empresa          ON tecnicos(id_empresa, activo);
CREATE INDEX idx_usuario_empresa          ON usuarios(id_empresa, activo);

-- Clientes y dispositivos
CREATE INDEX idx_cliente_empresa          ON clientes(id_empresa);
CREATE INDEX idx_dispositivo_cliente      ON dispositivos(id_cliente);
CREATE INDEX idx_dispositivo_empresa      ON dispositivos(id_empresa);

-- Reviews
CREATE INDEX idx_review_empresa           ON reviews(id_empresa, fecha_review DESC);


-- ============================================================
--  TRIGGERS
--  Nota: updated_at y fecha_registro pueden manejarse desde Hibernate
--  con @UpdateTimestamp y @CreationTimestamp.
-- ============================================================

CREATE OR REPLACE FUNCTION fn_actualizar_calificacion_marketplace()
RETURNS TRIGGER AS $$
DECLARE
    v_id_empresa BIGINT;
BEGIN
    v_id_empresa := COALESCE(NEW.id_empresa, OLD.id_empresa);

    UPDATE perfiles_marketplace
    SET calificacion_promedio = (
            SELECT COALESCE(ROUND(AVG(calificacion)::NUMERIC, 2), 0)
            FROM reviews
            WHERE id_empresa = v_id_empresa
        ),
        total_reviews = (
            SELECT COUNT(*)
            FROM reviews
            WHERE id_empresa = v_id_empresa
        ),
        fecha_actualizacion = NOW()
    WHERE id_empresa = v_id_empresa;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;

    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER trg_review_calificacion
    AFTER INSERT OR UPDATE OR DELETE ON reviews
    FOR EACH ROW EXECUTE FUNCTION fn_actualizar_calificacion_marketplace();


-- ============================================================
--  DATOS SEMILLA SUGERIDOS - estados estandar por empresa
-- ============================================================

-- Ejemplo al registrar una empresa nueva (id_empresa = 1):
--
-- INSERT INTO estados_reparacion
--     (id_empresa, nombre, orden, es_estado_final, notificar_cliente)
-- VALUES
--     (1, 'Solicitud recibida',     1,  FALSE, TRUE),
--     (1, 'Recepcion',              2,  FALSE, TRUE),
--     (1, 'Diagnostico',            3,  FALSE, FALSE),
--     (1, 'Cotizacion',             4,  FALSE, TRUE),
--     (1, 'Aprobado',               5,  FALSE, FALSE),
--     (1, 'Rechazado',              6,  TRUE,  TRUE),
--     (1, 'En reparacion',          7,  FALSE, FALSE),
--     (1, 'Control de calidad',     8,  FALSE, FALSE),
--     (1, 'Listo para entrega',     9,  FALSE, TRUE),
--     (1, 'Entregado',              10, TRUE,  TRUE),
--     (1, 'Cerrado',                11, TRUE,  FALSE);

-- Ejemplo de cuenta de cobro global:
--
-- INSERT INTO cuentas_cobro
--     (banco, tipo_cuenta, numero_cuenta, titular, moneda, instrucciones)
-- VALUES
--     ('Banco ejemplo', 'AHORRO', '0000-0000-0000', 'Kolvix', 'HNL',
--      'Enviar comprobante al correo o WhatsApp de soporte.');

-- Ejemplo de cuenta de pago del taller para sus clientes:
--
-- INSERT INTO cuentas_pago_taller
--     (id_empresa, banco, tipo_cuenta, numero_cuenta, titular, moneda, instrucciones)
-- VALUES
--     (1, 'Banco ejemplo', 'AHORRO', '1111-2222-3333', 'TechFix', 'HNL',
--      'Subir el comprobante desde el seguimiento web de la reparacion.');

-- Plantilla sugerida para inspeccion visual interactiva:
--
-- INSERT INTO plantillas_inspeccion
--     (id_categoria, nombre, descripcion, vistas)
-- VALUES
--     (
--         1,
--         'Smartphone generico',
--         'Zonas basicas para marcar danos fisicos en recepcion.',
--         '[
--             {
--                 "vista": "FRONTAL",
--                 "zonas": [
--                     {"id": "frontal_superior", "nombre": "Frontal superior", "x": 0, "y": 0, "width": 100, "height": 20},
--                     {"id": "pantalla", "nombre": "Pantalla", "x": 8, "y": 20, "width": 84, "height": 60},
--                     {"id": "frontal_inferior", "nombre": "Frontal inferior", "x": 0, "y": 80, "width": 100, "height": 20}
--                 ]
--             },
--             {
--                 "vista": "POSTERIOR",
--                 "zonas": [
--                     {"id": "camara", "nombre": "Camara", "x": 8, "y": 5, "width": 25, "height": 20},
--                     {"id": "tapa_posterior", "nombre": "Tapa posterior", "x": 5, "y": 25, "width": 90, "height": 65}
--                 ]
--             }
--         ]'::jsonb
--     );

-- Los albumes de evidencia son globales y ya quedan preestablecidos
-- en la semilla inicial. Al subir una evidencia, solo se referencia
-- el id_album correspondiente junto con la orden.

-- ============================================================
--  FIN DEL DDL
-- ============================================================
