spring.application.name=kolvix
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/kolvix_bd
spring.datasource.username=postgres
spring.datasource.password=sysdevjdz26
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# Subida de archivos (evidencias fotográficas)
kolvix.uploads.dir=uploads
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=12MB

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-only
spring.docker.compose.readiness.wait=always
