spring.application.name=kolvix
server.port=8080

# Configuración de la base de datos
spring.datasource.url=jdbc:postgresql://localhost:5432/kolvix_db
spring.datasource.username=postgres
spring.datasource.password="contraseña_segura"
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.docker.compose.enabled=false
spring.docker.compose.lifecycle-management=start-only
spring.docker.compose.readiness.wait=always
