name: Java Backend CI

on:
  push:
     # For testing this workflow , trigger on push to remote branch feature
    branches: [ "main", "dev", "feature" ]
    paths:
      - 'backend/**' 
  pull_request:
    branches: [ "main", "dev", "feature" ]
    paths:
      - 'backend/**'
     

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./backend

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Start PostgreSQL Database
      # Updated with the new database name (kolvix_bd) and password (sysdevjdz26)
      run: |
        docker build -t kolvix-db ./database
        docker run -d -p 5432:5432 \
          -e POSTGRES_USER=postgres \
          -e POSTGRES_PASSWORD=sysdevjdz26 \
          -e POSTGRES_DB=kolvix_bd \
          --health-cmd="pg_isready -U postgres -d kolvix_bd" \
          --health-interval=3s \
          --health-timeout=5s \
          --health-retries=10 \
          --name kolvix-postgres kolvix-db

    - name: Wait for Database to be Ready
      run: |
        echo "Waiting for PostgreSQL to initialize..."
        while [ "$(docker inspect -f '{{.State.Health.Status}}' kolvix-postgres)" != "healthy" ]; do
          sleep 2
        done
        echo "Database is initialized and ready!"

    - name: Compile and Test
      run: mvn clean compile test